
'use client'
import { useEffect } from "react";
 import axios from 'axios'
import { useState } from "react";
import { toast } from "react-toastify";


export default function opps() {


  useEffect(()=>{
     toast.success('this toast')
  },[])
  const [nam,setnam]=useState();

  console.log(nam)


let api= async()=>{

     const app= {name:'post'}
     const dta=  await axios.post('http://localhost:5050/',app)

  console.log(dta.data)

  
  // let res= await fetch('http://localhost:5050/');
  // let ress= await res.json();
  // console.log(ress)
}
   



  for(let a=0; a<5;a++){
    console.log(`my ${a} how is bater thien you ${a*2}`)
}

const con=()=>{
    console.log("hello sahil inida 😊")
}



console.log(nam)
  
    return (
      

        <div className="bg-gray-100 m-1">
  <button onClick={api()} className="bg-green-400">api call </button>

     <input placeholder="NAM " onChange={(e)=>setnam(e.target.value)}/>

    
  <div className="m-2 ">

<div className="flex">
<h1 className="  text-3xl tb:text-2xl m-auto   md: text-red-500"> vv java sript में opps कितने प्रकार के होते है      </h1> 

</div>


<p className="my-4">


जैसा की हम जानते है की programing languge  में कही  सारे concept होते है तो आज हम जानते है की 
की opps क्या होता है <span className="text-red-700 md:text-2xl ">what is opps </span> opps का concept आपको सारे programing languge me को मिल 
जायेगा तो हम जानते है की opps क्या है और कैसे काम करता है 
</p>

<div className="bg-red-500 flex  justify-center p-2 sm:w-[93%]  md:mx-[30%]">
<img src="../img/py.png" className="md:hover:animate-bounce duration-500 rounded-md "></img>
</div>
  <h1 className=" text-red-600 md:text-2xl  md:mx-[272px] ">why to use opps क्यों इस्तेमाल करे </h1>
<p>

java script में opps का use इस लिए किया जाता है जिससे हमको program करने में आसानी हो सके opps का काम होता 
है की program को आप एक बार लिख कर कही बार use कर सके <span className=" text-yellow-300   animate-bounce duration-700 ease-in-out">opps</span> के वजह से हमारा काम बहुत ही हो जाता है 
बिना opps के बिना भी हम code कर सकते है और program बना सकते है function का use कर के भी काम कर सकते है 
लेकिन एक अच्छा और batter programer वही है जिसको opps का concept आता हो 

</p>


<h1 className=" text-red-600 md:text-2xl  md:mx-[116px]    ">object oriented programming in हिंदी (oops in hindi ) </h1>
















,</div>





        
        </div>
    )
  
    
    }
    // export const head = {

    // }
    // export const metadata = {
    //   title: 'what is opps क्या होता है इसका use क्यों करे   ',
    //   description: 'Generated by create next app',
    // }

