

import { data } from "autoprefixer"







export default  function react  (){

  


// const a=[{name:"sahil inia", age:22, add:"khamriya"}]

// a.push({sir:"indai"})

// console.log(a)


 return(<>


<div className="m-2 p-1 bg-gray-100">
 <h1 className=" md:text-3xl tb:text-2xl md:ml-[233px] sm:text-[23px]   md:  text-red-500">react state in Hindi state क्या होता हो </h1>


 <div className="bg-red-500 flex  justify-center p-2 sm:w-[93%]  md:mx-[30%] rounded-lg">

<img src="./img/tt.png  "></img>
</div>
 < p className="m-y-4">


  
react js में state क्या  होता है और हम इसे क्यों इस्तेमाल करे और इसका क्या फायदा होता है react में 
तो आप लोगो को react js में state के बारे में जानना चाहते है तो उसेक लिए आप लोगो  को java script
आना चाहिए तभी आप लोगो लो react state के बारे में जानना चाहिए <span className="text-2xl text-red-500">react state in hindi</span> क्यूकि जब आप लोगो को java script
आती है तभी आप react में swtich करते है react js में state का use state managemnet करने में इस्तेमाल किया 
जाता है state menagement का मतलब की किसी स्थान को update करना और उसके स्थान पर नया data लाना 
इसी को हम react में state कहा जाता है react js में state एक बहुत ही मुख भूमिख है 
react में state एक hook होता है जिससे हम state ko managemnet करते है 
 </p>
<div className="bg-red-500 flex  justify-center p-2 sm:w-[93%]  md:mx-[30%] rounded-lg">

<img src="./img/r.PNG"></img>
</div>
 
<h1 className="  mt-4 mb-4 sm:text-[22px] md:text-3xl tb:text-2xl md:ml-[223px]   md:  text-red-500  mt-3">react state in Hindi (state क्या होता है ) </h1>
  

  <p>
 react in state तो हम जानते है है की react में state managemnet करते है तो हम जानते है की कैसे react state
 को step by step कैसे use करते है  और हम कैसे इसका इस्तेमाल से अपने काम को आसन बनाते है react के 
 applications में जिससे हमको काम करने में कोई भी परेशानी न हो और हम अपने काम अच्छे से कर पाए आइये जानते है 
 हम इसका इस्तेंमाल कैसे करते है 


  </p>
  <h1 className="  mt-4 mb-4 md:text-3xl tb:text-2xl sm:text-[22px] md:ml-[223px]   text-red-500">react state का use करे (Step by Step)  </h1>

<p>
  <span className="text-2xl text-red-400">Step 1 ..</span>
  सबसे पहले आपको react की application को install करना होगा लेकिन आपको ध्यान रहे की react ki application
  को install करने से पहले आपके system में Node js install होना चाहिए तभी आप react js का अपने system में use 
  कर पाएंगे तो पहले अगर आपको system me Node js न हो तो उसको install करे उसके बाद react js  install करे 

</p>

<p>
<span className="text-2xl text-red-400">Step 2 ..</span>
 
 जब आप Node js को system में install कर लेते है तब आप react js  को install  करे 
 तो जानते है कैसे करे ज  install हो जाये तो जिस भी file में आपको state का use करना हो तो पहले आप उस 
 file में state को import करना होगा उसके बाद आप उसका use कर पाएंगे 


</p>


<h1 className=" md:text-3xl tb:text-2xl sm:text-[22px] md:ml-[23px] mt-4 mb-4  text-red-500">how to import usestate hook in hindi (usestate import कैसे करे )  </h1>

<div className="bg-red-500 flex  justify-center p-2 sm:w-[93%] md:mx-[30%] rounded-lg">

<img src="./img/o.PNG" className=""></img>
</div>

<p className="mt-2">
react में state manage करने के लिए useState hook का use करना पड़ता है react में state का बहुत use किया जाता है 
बिना react useState hook के बिना आप react में state managemnet नही कर सकते है react  में आपको 
useState का बहुत ज्यदा ही use करना पड़ता  है  

</p>







 </div>














 </>)
}



export  const head = {

   
}
  export const metadata = {
  title: ' react usesatate in hindi state kasie use kare react me   ',
  description: 'Generated by create next app',
}